### ISSUE TITLE
出现的一些小问题和建议

### ISSUE THREAD

**Issue by lovelself** [Bililive/DGJv3#22]
1. 很多歌曲没有歌词显示；
2. 建议增加仅佩戴本人勋章才可点歌设置；
3. 源码下载下来后，生成dll后，点歌出现提示，400错误；
4. 怎么样才能加入，一起为点歌姬做贡献？

**Comment by Genteure** [comment]
1. 不是很有办法
2. 可以自己改，发 PR。近期不是很有精力维护这个项目，也不是很有兴趣维护这个项目。太麻烦了
3. 弹幕姬连接直播间
4. 直接发 PR
