### ISSUE TITLE
添加空闲歌单功能失效了

### ISSUE THREAD

**Issue by starsight** [Bililive/DGJv3#23]
弹幕姬日志信息为：
```
点歌姬 搜索:网易云音乐 获取歌单信息时出错 值不能为 null。
参数名: source
```
我看贴吧也有人反映这种问题，看了下源码有些没看懂,，似乎是API接口变了……
version:3.0.3

**Comment by Genteure** [comment]
点歌姬这个项目现在是暂停维护的状态，主要原因：

- 点歌姬这个项目维护了好几年了，实在是没有兴趣继续做了，维护起来很耗时间很烦
- 歌曲搜索量大，时不时就被屏蔽，折腾起来太费时费力了（说白了还是维护起来很耗时间很烦）
- 最近也很忙

添加空闲歌单功能不能用是几个月前因为被屏蔽严重加的限制，限制了每个 IP 每小时点歌数量，关掉了歌单搜索接口。
最近几个月到半年肯定不会有更新，并且很有可能以后都不会更了。
如果你想自己改来用、去掉限制的话，服务器侧可以参考 [Meting](https://github.com/metowolf/Meting) 项目。

ps,贴吧从来没有看过

**Comment by starsight** [comment]
好的，了解了，感谢这几年的更新谢谢~~
