### ISSUE TITLE
点歌、添加空闲歌曲、添加空闲歌单均会使整个弹幕姬出错、停止响应直至闪退。

### ISSUE THREAD

**Issue by AWhiteC** [Bililive/DGJv3#29]
![点歌姬错误](https://user-images.githubusercontent.com/40788545/99222248-1e278080-281d-11eb-84b6-e247abddd6ce.png)

不知道是有什么问题。也不知道我是否属于个例。
重复操作了无数遍……问题一再重现。至今没能正常使用点歌姬（已安装网易云本地曲库喵块和咪咕音乐插件）
版本：最新的3.0.5<del>，正在尝试下载老版本使用。</del>老版本依然出现同样的错误。
考虑到也有可能是电脑、弹幕姬本体问题，先从弹幕姬排除，只不过弹幕姬找了半天没找到老版本。
弹幕姬版本：1.1.1.49
附上日志
[B站彈幕姬錯誤報告.txt](https://github.com/Bililive/DGJv3/files/5553320/B.txt)

**Comment by Genteure** [comment]
本项目已经不再维护

`NAudio.MmException: NoDriver calling acmFormatSuggest` 印象中是因为 Windows 系统缺 Media Foundation 导致的，也有可能记错，你可以自己查一下。
